const types = {
  GET_BRANDS: "GET_BRANDS",
  BRAND_SELECTED: "BRAND_SELECTED",
  ATTACH_USER: "ATTACH_USER",
  SET_FOLLOWED_BRANDS: "SET_FOLLOWED_BRANDS",
  ADD_FOLLOWED_BRANDS: "ADD_FOLLOWED_BRANDS",
  REMOVE_FOLLOWED_BRANDS: "REMOVE_FOLLOWED_BRANDS",
  CREATE_USER: "CREATE_USER",
  DETACH_USER: "DETACH_USER",
  ENTER_SITE: "ENTER_SITE",
  GET_COLLECTIONS: "GET_COLLECTIONS",
  SET_LIKED_COLLECTIONS: "SET_LIKED_COLLECTIONS",
  ADD_LIKED_COLLECTIONS: "ADD_LIKED_COLLECTIONS",
  REMOVE_LIKED_COLLECTIONS: "REMOVE_LIKED_COLLECTIONS",
  COLLECTION_SELECTED: "COLLECTION_SELECTED",
  EXIT_BRAND: "EXIT_BRAND",
  GET_PITCHES: "GET_PITCHES",
  ADD_PITCH: "ADD_PITCH"

}

export default types;
