const types = {
  GET_BRANDS: "GET_BRANDS",
  BRAND_SELECTED: "BRAND_SELECTED",
  ATTACH_USER: "ATTACH_USER",
  SET_FOLLOWED_BRANDS: "SET_FOLLOWED_BRANDS",
  ADD_FOLLOWED_BRANDS: "ADD_FOLLOWED_BRANDS",
  REMOVE_FOLLOWED_BRANDS: "REMOVE_FOLLOWED_BRANDS"
}

export default types;
